name: Tag release and publish to npm
on: [workflow_dispatch]

env:
  NODE_AUTH_TOKEN: ${{secrets.GH_TOKEN}}

jobs:
  tag-release:
    name: Tag release and publish to npm
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
      - name: Tag release
        run: |
          yarn --frozen-lockfile
          yarn run release
          NEW_VERSION=v$(jq '.version' -r package.json)
          git ls-remote --exit-code --tags origin $NEW_VERSION || git tag $NEW_VERSION
          git push origin --tags
      - name: Publish to NPM
        run: npm publish
